# Load the import statements

In [2]:
import numpy as np
import pandas as pd

# Read the dataset using Pandas

In [25]:
data = pd.read_csv('./NLP-Task/nlpdata.txt',sep=',,,',header=None)

/home/subbareddy/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.


In [6]:
data.head()

0         1
0  how did serfdom develop in and then leave russ...   unknown
1  what films featured the character popeye doyle ?       what
2  how can i find a list of celebrities ' real na...   unknown
3  what fowl grabs the spotlight after the chines...      what
4                   what is the full form of .com ?       what

In [7]:
print(data[0],data[1])

0       how did serfdom develop in and then leave russ...
1       what films featured the character popeye doyle ? 
2       how can i find a list of celebrities ' real na...
3       what fowl grabs the spotlight after the chines...
4                        what is the full form of .com ? 
5       what contemptible scoundrel stole the cork fro...
6       what team did baseball 's st. louis browns bec...
7                        what is the oldest profession ? 
8                               what are liver enzymes ? 
9       name the scar-faced bounty hunter of the old w...
10                         when was ozzy osbourne born ? 
11       why do heavier objects travel downhill faster ? 
12                    who was the pride of the yankees ? 
13                                   who killed gandhi ? 
14      what is considered the costliest disaster the ...
15      what sprawling u.s. state boasts the most airp...
16      what did the only repealed amendment to the u....
17      how ma

In [8]:
#Remove the trailing spaces in labels
data[1] = data[1].str.strip()
data[1].value_counts()

what           609
who            402
unknown        272
affirmation    104
when            96
Name: 1, dtype: int64

# Convert categorical to numerical for label column using LabelEncoder

In [9]:
from sklearn.preprocessing import LabelEncoder
myencoder = LabelEncoder()
y = myencoder.fit_transform(data[1])

# Using BOW to convert each sentence to vector

In [132]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(max_features=60)
X = vectorizer.fit_transform(data[0])
print(vectorizer.get_feature_names())

['american', 'an', 'and', 'are', 'as', 'be', 'by', 'called', 'can', 'city', 'country', 'did', 'do', 'does', 'find', 'first', 'for', 'from', 'game', 'get', 'has', 'have', 'his', 'how', 'in', 'invented', 'is', 'it', 'made', 'man', 'many', 'mean', 'most', 'name', 'new', 'of', 'on', 'people', 'president', 'that', 'the', 'there', 'this', 'time', 'to', 'used', 'was', 'were', 'what', 'when', 'where', 'which', 'who', 'why', 'with', 'work', 'world', 'wrote', 'year', 'you']


In [133]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X.toarray(),y,test_size=0.2)

# Using decision tree classifier

In [134]:
from sklearn.tree import DecisionTreeClassifier
dt_model = DecisionTreeClassifier()
dt_model.fit(x_train,y_train)
y_pred = dt_model.predict(x_test)

In [135]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

             precision    recall  f1-score   support

          0       0.78      0.95      0.86        22
          1       0.93      0.86      0.90        65
          2       0.95      0.94      0.95       120
          3       0.79      0.73      0.76        15
          4       0.97      1.00      0.99        75

avg / total       0.93      0.93      0.93       297

[[ 21   1   0   0   0]
 [  6  56   2   1   0]
 [  0   3 113   2   2]
 [  0   0   4  11   0]
 [  0   0   0   0  75]]


In [136]:
from sklearn.model_selection import cross_val_score
print(cross_val_score(dt_model,X,y,cv=5))

[0.93979933 0.89597315 0.94594595 0.91554054 0.93537415]


# Using Logistic Regression Model

In [137]:
from sklearn.linear_model import LogisticRegression
lr_model = LogisticRegression()
lr_model.fit(x_train,y_train)
y_pred = lr_model.predict(x_test)

In [138]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

             precision    recall  f1-score   support

          0       0.89      0.77      0.83        22
          1       0.92      0.92      0.92        65
          2       0.96      0.99      0.98       120
          3       0.92      0.80      0.86        15
          4       0.99      1.00      0.99        75

avg / total       0.95      0.95      0.95       297

[[ 17   5   0   0   0]
 [  2  60   2   1   0]
 [  0   0 119   0   1]
 [  0   0   3  12   0]
 [  0   0   0   0  75]]


In [139]:
from sklearn.model_selection import cross_val_score
print(cross_val_score(lr_model,X,y,cv=5))

[0.95986622 0.93959732 0.96959459 0.94594595 0.96938776]


In [140]:
from nltk.corpus import stopwords
stopWords = set(stopwords.words('english'))

# Don't remove stopwords - because when, where, who,why,how all these words belongs to stopwords

In [141]:
print(stopWords)

{'it', 'mustn', "won't", 'does', 've', "weren't", 'that', 'these', 'only', 'or', "hasn't", 'and', 'wouldn', 'been', 'ourselves', 'themselves', 'of', 'needn', 'in', 'same', 'she', 'some', 'ma', 'yourselves', 'nor', 'myself', 'both', 'yourself', 'what', "hadn't", 'which', 'down', 'for', 'other', 'm', 'own', 'are', 'has', "isn't", 'mightn', 'll', 'further', 'under', 'so', 'before', "you're", 'again', 'y', 'you', "doesn't", "needn't", 'them', 'won', 'yours', 'the', 'hers', 'just', 'because', 'having', 'hasn', 'am', 'over', 'were', "couldn't", 'through', 'to', 'their', 'herself', 'at', 'about', "mustn't", 'wasn', 'this', 'isn', 'against', 'can', 'they', 'is', 'until', 'him', 'whom', 'than', 'who', 'my', 'where', 'couldn', 'did', "you'd", "don't", 'didn', 's', 'each', 'between', 'into', 'no', 'very', 'all', 'with', "shan't", 'why', 'any', 'me', 'haven', 'not', 'but', "wasn't", 'how', "aren't", 'being', 'out', 'then', 'too', 'few', 'have', 'from', 'off', 't', 'had', 'if', 'such', 'there', 'ou

In [142]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(max_features=50)
X_tf = vectorizer.fit_transform(data[0])
print(vectorizer.get_feature_names())

['american', 'an', 'and', 'are', 'as', 'be', 'by', 'can', 'city', 'country', 'did', 'do', 'does', 'find', 'first', 'for', 'from', 'get', 'has', 'have', 'his', 'how', 'in', 'invented', 'is', 'it', 'many', 'most', 'name', 'of', 'on', 'people', 'president', 'that', 'the', 'there', 'this', 'to', 'was', 'were', 'what', 'when', 'where', 'which', 'who', 'with', 'work', 'world', 'wrote', 'you']


In [143]:
x_train,x_test,y_train,y_test = train_test_split(X_tf.toarray(),y,test_size=0.2)

In [144]:
dt_model = DecisionTreeClassifier()
dt_model.fit(x_train,y_train)
y_pred = dt_model.predict(x_test)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

             precision    recall  f1-score   support

          0       0.83      0.80      0.82        25
          1       0.78      0.84      0.81        45
          2       0.93      0.96      0.94       121
          3       0.91      0.69      0.78        29
          4       1.00      1.00      1.00        77

avg / total       0.91      0.91      0.91       297

[[ 20   5   0   0   0]
 [  3  38   3   1   0]
 [  0   4 116   1   0]
 [  1   2   6  20   0]
 [  0   0   0   0  77]]


In [145]:
lr_model = LogisticRegression()
lr_model.fit(x_train,y_train)
y_pred = lr_model.predict(x_test)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

             precision    recall  f1-score   support

          0       0.95      0.80      0.87        25
          1       0.89      0.89      0.89        45
          2       0.90      1.00      0.95       121
          3       1.00      0.69      0.82        29
          4       1.00      1.00      1.00        77

avg / total       0.94      0.94      0.93       297

[[ 20   4   1   0   0]
 [  1  40   4   0   0]
 [  0   0 121   0   0]
 [  0   1   8  20   0]
 [  0   0   0   0  77]]


In [146]:
from sklearn.neighbors import  KNeighborsClassifier
knn_model = KNeighborsClassifier(metric='jaccard')
knn_model.fit(x_train,y_train)
y_pred = knn_model.predict(x_test)
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

             precision    recall  f1-score   support

          0       1.00      0.76      0.86        25
          1       0.87      0.87      0.87        45
          2       0.88      0.98      0.93       121
          3       1.00      0.66      0.79        29
          4       0.99      1.00      0.99        77

avg / total       0.93      0.92      0.92       297

[[ 19   2   4   0   0]
 [  0  39   5   0   1]
 [  0   2 119   0   0]
 [  0   2   8  19   0]
 [  0   0   0   0  77]]
